# -*- coding: utf-8 -*-
"""un_nouveau_streamlit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dLkZawlLgOML85Y5BGa3EzpwaXMdgnOY
"""

!pip install streamlit
import streamlit as st

st.write('Hello world!!')

